name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read # Needed to clone this repository

jobs:
  discover-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.find.outputs.modules }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: find
        run: |
          # Find all go.mod files that are components (exclude internal/tools).
          modules=$(find . -name go.mod -not -path './internal/*' -exec dirname {} \; | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "modules=${modules}" >> "$GITHUB_OUTPUT"

  lint:
    needs: discover-modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.discover-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.10.1
          working-directory: ${{ matrix.module }}

  test:
    needs: discover-modules
    runs-on: 'ubuntu-${{ matrix.arch }}-large'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.discover-modules.outputs.modules) }}
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Run tests
        working-directory: ${{ matrix.module }}
        run: go test -race ./...
